---
Resources:
  MyEC2Instance:
      Type: AWS::EC2::Instance
      Properties:
        AvailabilityZone: us-east-1a
        ImageId: ami-084568db4383264d4
        InstanceType: t2.micro

Outputs:
  InstanceId:
    Description: The ID of the EC2 instance
    Value: !Ref MyEC2Instance
  InstancePublicIP:
    Description: The public IP address of the EC2 instance
    Value: !GetAtt MyEC2Instance.PublicIp
  InstancePrivateIP:
    Description: The private IP address of the EC2 instance
    Value: !GetAtt MyEC2Instance.PrivateIp